export const GALLERY_IMAGES = [
  {
    src: "/images/2.jpg",
    alt: "Kim and Nicola at the beach",
    width: 800,
    height: 800,
    },
    {
      src: "/images/3.jpg",
      alt: "Kim and Nicola hiking",
      width: 800,
      height: 800,
    },
    {
      src: "/images/4.jpg",
      alt: "Kim and Nicola at a restaurant",
      width: 800,
      height: 800,
    },
    {
      src: "/images/5.jpg",
      alt: "Kim and Nicola traveling",
      width: 800,
      height: 800,
    },
    {
      src: "/images/6.jpg",
      alt: "Kim and Nicola at a concert",
      width: 800,
      height: 800,
    },
    {
      src: "/images/7.jpg",
      alt: "Kim and Nicola at home",
      width: 800,
      height: 800,
    },
    {
      src: "/images/8.jpg",
      alt: "Kim and Nicola with friends",
      width: 800,
      height: 800,
    },
    {
      src: "/images/9.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/10.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/11.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/12.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/13.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/14.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/15.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/16.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/17.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/18.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/19.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/20.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/21.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/22.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/23.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/24.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/25.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    },
    {
      src: "/images/26.jpg",
      alt: "Kim and Nicola engagement photo",
      width: 800,
      height: 800,
    }
  ];